
[theme]
primaryColor="#4CAF50"
backgroundColor="#b09aed"
secondaryBackgroundColor="#F0F2F6"
textColor="#000005"
font="sans serif"

[styles]
css="""
body{
    font-family: 'Arial',sans serif;
}
h1,h2,h3,h4,h5,h6 {
    font-family: 'Calibri',seif;
}
"""

[ui]
pageTitle = "TESTING TOML"
pageIcon = ":smiley:"