[theme]
primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
[styles]
css="""
body {
    font-family: 'Arial',sans serif;
}
h1,h2,h3,h4,h5,h6 {
    font-family: 'Calibri',serif;
}
"""
[ui]
pageTitle = "TESTING TOML"
pageIcon = ":smiley:"